name: AuthService CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout authService
      - name: Checkout authService
        uses: actions/checkout@v4
      
      # 2️⃣ Gerar JWT_SECRET dinâmico
      - name: Generate JWT secret
        run: echo "JWT_SECRET=$(openssl rand -hex 32)" >> $GITHUB_ENV

      # 3️⃣ Subir ambiente de teste
      - name: Setup Ambiente
        run: |
          docker compose --profile test up -d --build

      # 4️⃣ Parar e remover containers
      - name: Stop and remove containers
        if: always()
        run: |
          docker compose --profile test down -v

      # 5️⃣ Salvar relatório
      - name: Save report html to artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-newman
          path: reports/relatorio.html
          if-no-files-found: warn